# Generated by Django 4.2 on 2023-05-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_title', models.CharField(max_length=150)),
                ('eng_title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('publishing_house', models.CharField(max_length=150)),
                ('chapter', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('manga', 'manga'), ('manhua', 'manhua'), ('rumanga', 'rumanga'), ('comics', 'comics')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('issue_year', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='manga.author')),
                ('genre', models.ManyToManyField(related_name='manga', to='manga.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[[1, '*'], [2, '**'], [3, '***'], [4, '****'], [5, '*****'], [6, '******'], [7, '*******'], [8, '********'], [9, '*********'], [10, '**********']], default=1)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='manga.manga')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manga.manga')),
            ],
        ),
    ]
